apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration:v1.1.1
  namespace: easyshop
spec:
  template:
    spec:
      containers:
      - name: migration:v1.1.1
        image: nileshfatfatwale/migration:v1.1.1
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
