apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  NEXTAUTH_SECRET: "HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw="
  JWT_SECRET: "<password>"

---

apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
type: Opaque
stringData:
  username: "nilesh-fatfatwale"
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: gmail-smtp-creds
  namespace: argocd
type: Opaque
stringData:
  email-username: "fatfatwalenilesh@gmail.com"
  email-password: "password"
